#!/usr/bin/env python3
"""Generate the public provider table from the validated TOML contract."""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "support-matrix.toml"
OUTPUT = ROOT / "docs" / "support-matrix.md"


def cell(value: object) -> str:
    """Render a value safely inside a Markdown table cell."""
    text = str(value).replace("\\", "\\\\").replace("|", "\\|")
    return " ".join(text.splitlines()).strip()


def render(document: dict[str, object]) -> str:
    providers = document.get("providers")
    if not isinstance(providers, list):
        raise ValueError("providers must be an array")

    lines = [
        "# Provider Support Matrix",
        "",
        "<!-- Generated by scripts/generate-support-matrix.py; do not edit. -->",
        "",
        "This table is generated from [`support-matrix.toml`](../support-matrix.toml).",
        "Capability claims remain subject to the consistency and platform restrictions",
        "documented by each provider.",
        "",
        "| Provider | ID | Implemented | Current maturity | v1 target | Platforms | Capabilities | Optional capabilities | Mechanism |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for provider in providers:
        if not isinstance(provider, dict):
            raise ValueError("each provider must be a table")
        capabilities = ", ".join(provider.get("capabilities", []))
        optional = "; ".join(provider.get("optional_capabilities", [])) or "None"
        values = (
            provider.get("display_name", ""),
            f"`{provider.get('id', '')}`",
            "Yes" if provider.get("implemented") is True else "No",
            provider.get("maturity", ""),
            provider.get("v1_target", ""),
            ", ".join(provider.get("platforms", [])),
            capabilities,
            optional,
            provider.get("mechanism", ""),
        )
        lines.append("| " + " | ".join(cell(value) for value in values) + " |")
    lines.extend(
        (
            "",
            "Current maturity describes shipped evidence today; v1 target is the maximum tier intended for the 1.0 release.",
            "Both labels describe this implementation, not the upstream hypervisor.",
        )
    )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated output is stale")
    parser.add_argument("--source", type=Path, default=SOURCE)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args(argv)

    try:
        document = tomllib.loads(args.source.read_text(encoding="utf-8"))
        generated = render(document)
        if args.check:
            current = args.output.read_text(encoding="utf-8")
            if current != generated:
                print(f"{args.output}: generated support matrix is stale", file=sys.stderr)
                return 1
        else:
            args.output.write_text(generated, encoding="utf-8", newline="\n")
    except (OSError, tomllib.TOMLDecodeError, ValueError) as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
